package com.perpetuum.issue_tracker.model;

import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Issue entity
 *
 * Represents a single issue record stored in Google Sheets.
 * 
 * Fields:
 * - id: unique identifier (generated by IssueService)
 * - description: short text describing the issue
 * - parentId: optional reference to another issue (for hierarchy)
 * - status: current status of the issue (OPEN, IN_PROGRESS, CLOSED)
 * - createdAt: timestamp when issue was created
 * - updatedAt: timestamp when issue was last updated
 *
 * Uses Lombok annotations for boilerplate code generation:
 * - @Data: generates getters, setters, equals, hashCode, toString
 * - @Builder: provides builder pattern
 * - @NoArgsConstructor and @AllArgsConstructor: constructor generation
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Issue {
    private String id;
    private String description;
    private String parentId;
    private Status status; 
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
